# hlf-tools - a layer on top of hyperledger/fabric-tools 8-1-19 @bjay
ARG base_tag="latest"
FROM athena-docker-local.artifactory.eng.vmware.com/fabric-tools:${base_tag}

# WORKDIR /
# RUN mkdir hlfdata
# COPY ./docker/hlf /hlfdata

# HLF_HARDCODED_CONFIG

#assuming local structure from  vmwathena_blockchain git repo  

COPY ./crypto-config /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
COPY ./configtx-peer1/ /etc/hyperledger/configtx
COPY ./scripts/initialize_channel.sh /opt/gopath/src/github.com/hyperledger/fabric/peer/

ENV GOPATH=/opt/gopath
ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV FABRIC_LOGGING_SPEC=info
ENV CORE_PEER_ID=cli
ENV CORE_PEER_ADDRESS=peer1.org1.example.com:7051
ENV CORE_ORDERER_ADDRESS=orderer1.example.com:7050
ENV CORE_PEER_LOCALMSPID=Org1MSP
ENV CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
ENV CORE_CHAINCODE_KEEPALIVE=10

# _HLF_HARDCODED_CONFIG

WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/

CMD ["/bin/bash","./peer/initialize_channel.sh"]

