# hlf-orderer - a layer on top of hyperledger/fabric-orderer 8-1-19 @bjay
ARG base_tag="latest"
FROM athena-docker-local.artifactory.eng.vmware.com/fabric-orderer:${base_tag}

# HLF_HARDCODED_CONFIG

#assuming local structure from  vmwathena_blockchain git repo  

COPY ./configtx-peer1/ /etc/hyperledger/configtx
COPY ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/ /etc/hyperledger/msp/orderer
COPY ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/ /etc/hyperledger/msp/peerOrg1

#only used for channel 
EXPOSE 7050


ENV ORDERER_GENERAL_LOGLEVEL=info
ENV ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
ENV ORDERER_GENERAL_LISTENPORT=7050
ENV ORDERER_GENERAL_GENESISMETHOD=file
ENV ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
ENV ORDERER_GENERAL_LOCALMSPID=OrdererMSP
ENV ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
ENV ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo

# _HLF_HARDCODED_CONFIG

WORKDIR /opt/gopath/src/github.com/hyperledger/fabric/orderer

CMD ["orderer"]