version: 1

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:18.04"
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'mkdir build && cd build && cmake -DBUILD_TESTING=1 ..'
      - run:
          name: Creating Binary Files
          command: 'make -j4'
      - run:
          name: Run Unit Testing
          command: 'make test'
