version: 1

jobs:
  build:
    docker:
      - image: "circleci/buildpack-deps:18.04"
    steps:
      - run:
          name: Installing toolchain
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++ cmake clang-format libgmp3-dev python3 python3-pip python3-setuptools openssl libssl-dev'
      - run:
          name: Installing Python dependencies
          command: 'python3 -m pip install --upgrade trio'
      - run:
          name: Install RELIC
          command: |
             cd
             git clone https://github.com/relic-toolkit/relic
             cd relic
             git checkout b984e901ba78c83ea4093ea96addd13628c8c2d0
             mkdir build
             cd build
             cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DALLOC=AUTO -DWSIZE=64 -DRAND=UDEV -DSHLIB=ON -DSTLIB=ON -DSTBIN=OFF -DTIMER=HREAL -DCHECK=on -DVERBS=on -DARITH=x64-asm-254 -DFP_PRIME=254 -DFP_METHD="INTEG;INTEG;INTEG;MONTY;LOWER;SLIDE" -DCOMP="-O3 -funroll-loops -fomit-frame-pointer -finline-small-functions -march=native -mtune=native" -DFP_PMERS=off -DFP_QNRES=on -DFPX_METHD="INTEG;INTEG;LAZYR" -DPP_METHD="LAZYR;OATEP" ..
             make -j4
             sudo make install
      - run:
          name: Install CryptoPP
          command: |
              cd
              git clone https://github.com/weidai11/cryptopp.git
              cd cryptopp
              git checkout CRYPTOPP_8_2_0;
              make -j4
              sudo make install
      - checkout
      - run:
          name: Init submodules
          command: |
             cd ~/project
             git submodule init
             git submodule update --recursive
      - run:
          name: Running CMake
          command: |
              cd ~/project
              mkdir build
              cd build
              cmake -DBUILD_TESTING=1 ..
      - run:
          name: Building
          command: 'cd ~/project/build && make -j4'
      - run:
          name: Run Unit Testing
          command: 'cd ~/project/build && sudo make test'
