#!/bin/bash

TOOLS_IMAGE='$(docker images | sed -nE '"'"'s#^(.*committer-tools)\s+(\S*)\s.*$#\1:\2#p'"'"')'

CONCORD_CONFIG=/config/concord/config-local/concord.config:/config/concord/config-local/concord.config
HOST_IP='$(ip addr show eth0 | sed -nE '"'"'s#^.*inet (.*)/.*$#\1#p'"'"')'

echo "docker run -it -v ${CONCORD_CONFIG} -e HOST_IP=${HOST_IP} ${TOOLS_IMAGE} bash"
