#!/bin/bash
#
# This script is for distributing Concord configuration files in the
# Docker-based test cluster; this script is intended to copy the configuration
# files generated by the Concord configuration generation utility's container
# to the environments in which the Concord nodes' containers run. This script
# takes arguments for the sources and destinations of the configuration files to
# move; if no arguments are provided, the default values this script uses are
# such that, if this script is launched from the vmathena_blockchain/docker
# directory, it should move the configuration files generated for the 4-node
# Concord test cluster in Docker.
#
# Arguments:
#  1:   Path and prefix common to the configuration files as the configuration
#       generation utility has produced them; it is expected the files will have
#       names <PREFIX>1.config, <PREFIX>2.config, etc. For example, if <PREFIX>
#       is ./config-public/concord, this script will look for the configuration
#       files at ./config-public/concord1.config,
#       ./config-public/concord2.config, etc.
#  2-N: Target paths to move the configuration files to.

if [[ $# -gt 0 ]]; then
    PUBPATH=$1
    shift
else
    PUBPATH="./config-public/concord"
fi

if [[ $# -gt 0 ]]; then
    PRIVPATHS=("$@")
else
    # Default
    PREFIX="./config-concord"
    SUFFIX="/concord.config"
    for f in $(ls config-public/concord*.config); do
        # Get the replica number
        NUM=${f%.config}
        NUM=${NUM##*/concord}

        # Create destination directory
        mkdir -p ${PREFIX}${NUM}

        PRIVPATHS+=("${PREFIX}${NUM}${SUFFIX}")
    done
fi

for i in $(seq 1 ${#PRIVPATHS[@]}); do
    CONFIGPATH="${PUBPATH}${i}.config"
    mv -f ${CONFIGPATH} "${PRIVPATHS[i - 1]}"
done
