daml_enable: true
eth_enable: false
client_proxies_per_replica: 4
num_of_external_clients: 15
c_val: 0
f_val: 1
concord-bft_communication_buffer_length: 16777216
concord-bft_max_external_message_size: 16777216
concord-bft_max_reply_message_size: 4096
concord-bft_max_num_of_reserved_pages: 50
tls_cipher_suite_list: ECDHE-ECDSA-AES256-GCM-SHA384
tls_certificates_folder_path: ./tls_certs
comm_to_use: tls
FEATURE_time_service: true
key_exchange_on_start: true
preexecution_enabled: true
signing_key_path: /concord/signing_keys
node__TEMPLATE:
  logger_config: /concord/config-public/log4cplus.properties
  genesis_block: /concord/config-public/daml_genesis.json
  blockchain_db_path: /concord/rocksdbdata/
  time_pusher_period_ms: 1000
  bft_client_timeout_ms: 4294967295
  jaeger_agent: jaeger-agent:6831
  metrics_config: /concord/config-public/metrics_config.yaml
  prometheus_port: 9891
  FEATURE_daml_pipelined_commits: true
node:
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source1
    daml_execution_engine_addr: daml_execution_engine1:55000
    replica:
      - replica_host: concord1
        replica_port: 3501
    client_proxy:
      - client_host: concord1
        client_port: 3502
      - client_host: concord1
        client_port: 3503
      - client_host: concord1
        client_port: 3504
      - client_host: concord1
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source2
    daml_execution_engine_addr: daml_execution_engine1:55000
    replica:
      - replica_host: concord2
        replica_port: 3501
    client_proxy:
      - client_host: concord2
        client_port: 3502
      - client_host: concord2
        client_port: 3503
      - client_host: concord2
        client_port: 3504
      - client_host: concord2
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source3
    daml_execution_engine_addr: daml_execution_engine1:55000
    replica:
      - replica_host: concord3
        replica_port: 3501
    client_proxy:
      - client_host: concord3
        client_port: 3502
      - client_host: concord3
        client_port: 3503
      - client_host: concord3
        client_port: 3504
      - client_host: concord3
        client_port: 3505
  - service_host: 0.0.0.0
    service_port: 5458
    time_source_id: time-source4
    daml_execution_engine_addr: daml_execution_engine1:55000
    replica:
      - replica_host: concord4
        replica_port: 3501
    client_proxy:
      - client_host: concord4
        client_port: 3502
      - client_host: concord4
        client_port: 3503
      - client_host: concord4
        client_port: 3504
      - client_host: concord4
        client_port: 3505
