#!/bin/bash

FLUENT_CONF_LOG_INTELLIGENCE="/fluentd/etc/fluent-log-intelligence.conf"
FLUENT_CONF_LOG_INSIGHT="/fluentd/etc/fluent-log-insight.conf"
LOG_INTELLIGENCE="LOG_INTELLIGENCE"
LOG_INSIGHT="LOG_INSIGHT"

if [ "$LOG_DESTINATION" = $LOG_INTELLIGENCE ]; then
  cp $FLUENT_CONF_LOG_INTELLIGENCE $FLUENT_CONF
  sed -i 's/LINT_ENDPOINT_URL/'"$LINT_ENDPOINT_URL"'/g' $FLUENT_CONF
  sed -i 's/LINT_API_KEY/'"$LINT_API_KEY"'/g' $FLUENT_CONF
else
  cp $FLUENT_CONF_LOG_INSIGHT $FLUENT_CONF
  sed -i 's/LOG_INSIGHT_HOST/'"$LOG_INSIGHT_HOST"'/g' $FLUENT_CONF
  sed -i 's/LOG_INSIGHT_PORT/'"$LOG_INSIGHT_PORT"'/g' $FLUENT_CONF
  sed -i 's/LOG_INSIGHT_AGENT_ID/'"$LOG_INSIGHT_AGENT_ID"'/g' $FLUENT_CONF
fi

exec "$@"
