# for running local concord with Test Execution Engine
#
# ./gen-docker-concord-config.sh config-public/dockerConfigurationInput-tee.yaml
# docker-compose -f docker-compose-tee.yml up
#
version: '3'
services:
  concord1:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - "50051:50051"
      - "4501:4501/udp"
    expose:
      - 9891
      - 5458
      - 3501/udp
    volumes:
      - ./devdata/rocksdbdata1:/concord/rocksdbdata
      - ./devdata/log1:/concord/log
      - ./devdata/securestore1:/concord/config-generated
      - ./config-concord1:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
      - ./devdata/core1:/concord/cores

  concord2:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - "50052:50051"
      - "4502:4501/udp"
    expose:
      - 5458
      - 9891
      - 3501/udp
    volumes:
      - ./devdata/rocksdbdata2:/concord/rocksdbdata
      - ./devdata/log2:/concord/log
      - ./devdata/securestore2:/concord/config-generated
      - ./config-concord2:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
      - ./devdata/core2:/concord/cores

  concord3:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - "50053:50051"
      - "4503:4501/udp"
    expose:
      - 5458
      - 9891
      - 3501/udp
    volumes:
      - ./devdata/rocksdbdata3:/concord/rocksdbdata
      - ./devdata/log3:/concord/log
      - ./devdata/securestore3:/concord/config-generated
      - ./config-concord3:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
      - ./devdata/core3:/concord/cores

  concord4:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    ports:
      - "50054:50051"
      - "4504:4501/udp"
    expose:
      - 5458
      - 9891
      - 3501/udp
    volumes:
      - ./devdata/rocksdbdata4:/concord/rocksdbdata
      - ./devdata/log4:/concord/log
      - ./devdata/securestore4:/concord/config-generated
      - ./config-concord4:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./tls_certs:/concord/tls_certs:ro
      - ./devdata/core4:/concord/cores
