## Node4 image
FROM athenabase

COPY resources/athena4.config /athena/resources/
RUN sed -i -e "s/tmp/athena\/resources/g" /athena/resources/athena4.config

COPY resources/sbft/*04.priv \
     resources/sbft/*08.priv \
     resources/sbft/*12.priv \
     resources/sbft/*16.priv \
     /athena/resources/sbft/

WORKDIR /athena
CMD export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && \
    /athena/resources/find-docker-instances.sh \
       /athena/resources/sbft/*.pub athena1 athena2 athena3 athena4 && \
    /athena/athena -c /athena/resources/athena4.config
# athena<->helen
EXPOSE 5461
# SBFT
EXPOSE 3504/udp
EXPOSE 3508/udp
EXPOSE 3512/udp
EXPOSE 3516/udp
EXPOSE 3520/udp
