## Node1 image
FROM athenabase

COPY resources/athena1.config /athena/resources/
RUN sed -i -e "s/tmp/athena\/resources/g" /athena/resources/athena1.config

COPY resources/sbft/*01.priv \
     resources/sbft/*05.priv \
     resources/sbft/*09.priv \
     resources/sbft/*13.priv \
     /athena/resources/sbft/

WORKDIR /athena
CMD export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && \
    /athena/resources/find-docker-instances.sh \
       /athena/resources/sbft/*.pub athena1 athena2 athena3 athena4 && \
    /athena/athena -c /athena/resources/athena1.config
# athena<->helen
EXPOSE 5458
# SBFT
EXPOSE 3501/udp
EXPOSE 3505/udp
EXPOSE 3509/udp
EXPOSE 3513/udp
EXPOSE 3517/udp
