# For running DAML and RO replica.
# This file is meant to be an extension to docker-compose-daml-nano.yml. It adds
# additional RO replica and S3 service.
#
# ./gen-docker-concord-config.sh config-public/dockerConfigurationInput-daml-nano-ro.yaml
# docker-compose -f docker-compose-daml-nano.yml -f docker-compose-daml-nano-ro.yml up
#
version: '3'
services:
  concord5:
    image: "${concord_repo}:${concord_tag}"
    privileged: true
    depends_on:
      - daml_execution_engine1
    ports:
      - "50055:50051"
    expose:
      - 5458
      - 9891
      - 3501/udp
    volumes:
      - ./devdata/rocksdbdata5:/concord/rocksdbdata
      - ./devdata/log5:/concord/log
      - ./devdata/securestore5:/concord/config-generated
      - ./config-concord5:/concord/config-local
      - ./config-public:/concord/config-public:ro
      - ./signing_keys:/concord/signing_keys:ro
      - ./tls_certs:/concord/tls_certs:ro
      - ./trs_trc_tls_certs:/concord/trs_trc_tls_certs:ro

  minio:
    image: minio/minio:RELEASE.2020-09-05T07-14-49Z 
    command: server /data
    expose:
      - "9000/tcp"
    environment:
      - MINIO_ACCESS_KEY=concordbft
      - MINIO_SECRET_KEY=concordbft
    volumes:
      - ./devdata/minio-buckets:/data
    entrypoint: >
      /bin/sh -c "
      mkdir /data/blockchain;
      /usr/bin/docker-entrypoint.sh server /data"