## Node3 image
FROM athenabase

COPY resources/athena3.config /athena/resources/
RUN sed -i -e "s/tmp/athena\/resources/g" /athena/resources/athena3.config

COPY resources/sbft/*03.priv \
     resources/sbft/*07.priv \
     resources/sbft/*11.priv \
     resources/sbft/*15.priv \
     /athena/resources/sbft/

WORKDIR /athena
CMD export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && \
    /athena/resources/find-docker-instances.sh \
       /athena/resources/sbft/*.pub athena1 athena2 athena3 athena4 && \
    /athena/athena -c /athena/resources/athena3.config
# athena<->helen
EXPOSE 5460
# SBFT
EXPOSE 3503/udp
EXPOSE 3507/udp
EXPOSE 3511/udp
EXPOSE 3515/udp
EXPOSE 3519/udp
