# hlf-peer - a layer on top of hyperledger/fabric-peer 8-1-19 @bjay
ARG base_tag="latest"
FROM athena-docker-local.artifactory.eng.vmware.com/fabric-peer:${base_tag}

# HLF_HARDCODED_CONFIG

#assuming local structure from  vmwathena_blockchain git repo  
COPY ./docker/hlf/configtx-peer1/ /etc/hyperledger/configtx
COPY ./docker/hlf/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp /etc/hyperledger/msp/peer 
COPY ./docker/hlf/crypto-config/peerOrganizations/org1.example.com/users /etc/hyperledger/msp/users

#only used for channel 
EXPOSE 7051

ENV CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
ENV CORE_PEER_ID=peer1.org1.example.com
ENV CORE_LOGGING_LEVEL=INFO
ENV CORE_LOGGING_PEER=DEBUG
ENV CORE_CHAINCODE_LOGGING_LEVEL=debug
ENV CORE_PEER_LOCALMSPID=Org1MSP
ENV CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
ENV CORE_PEER_ADDRESS=peer1.org1.example.com:7051
ENV CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
ENV CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric
ENV CORE_CONCORD_ADDRESS=concord:50052

# _HLF_HARDCODED_CONFIG

WORKDIR /opt/gopath/src/github.com/hyperledger/fabric

CMD ["peer","node","start"]
