## Node2 image
FROM athenabase

COPY resources/athena2.config /athena/resources/
RUN sed -i -e "s/tmp/athena\/resources/g" /athena/resources/athena2.config

COPY resources/sbft/*02.priv \
     resources/sbft/*06.priv \
     resources/sbft/*10.priv \
     resources/sbft/*14.priv \
     /athena/resources/sbft/

WORKDIR /athena
CMD export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && \
    /athena/resources/find-docker-instances.sh \
       /athena/resources/sbft/*.pub athena1 athena2 athena3 athena4 && \
    /athena/athena -c /athena/resources/athena2.config
# athena<->helen
EXPOSE 5459
# SBFT
EXPOSE 3502/udp
EXPOSE 3506/udp
EXPOSE 3510/udp
EXPOSE 3514/udp
EXPOSE 3518/udp
