version: '3'
services:
  concord1:
    image: "${memleak_concord_repo}:${memleak_concord_tag}"
    command:
      - valgrind
      - -v
      - --leak-check=full
      - --show-leak-kinds=all
      - --track-origins=yes
      - --log-file=/tmp/valgrind_concord1.log
      - --suppressions=/concord/concord.supp
      - /concord/concord
      - -a
      - /concord/config-local/application.config
      - -d
      - /concord/config-local/deployment.config
      - -s
      - /concord/config-local/secrets.config
    volumes:
      - /tmp:/tmp
      - ./tls_certs:/concord/tls_certs:ro
  helen:
    volumes:
      - ./config-helen:/config:ro
    command:
      - java
      - -Dspring.config.location=/config/app/profiles/,./
      - -Dspring.profiles.active=test
      - -jar
      - blockchain-helen.jar
      - --ConcordAuthorities=concord1:5458
