/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni */
#ifndef _Include_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni
#define _Include_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.digitalasset.daml.on.vmware.write.service.bft.BftConcordClientPoolJni
 * Method:    currentHealth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni_currentHealth
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.write.service.bft.BftConcordClientPoolJni
 * Method:    sendRequest
 * Signature: ([BJZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni_sendRequest
  (JNIEnv *, jobject, jbyteArray, jlong, jboolean, jstring);

/*
 * Class:     com.digitalasset.daml.on.vmware.write.service.bft.BftConcordClientPoolJni
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni_close
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.write.service.bft.BftConcordClientPoolJni
 * Method:    initialize
 * Signature: (Ljava/lang/String;)S
 */
JNIEXPORT jshort JNICALL Java_com_digitalasset_daml_on_vmware_write_service_bft_BftConcordClientPoolJni_initialize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

