# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import performance_pb2 as performance__pb2


class PerformanceServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PerfInit = channel.unary_unary(
        '/com.vmware.concord.performance.PerformanceService/PerfInit',
        request_serializer=performance__pb2.PerfInitRequest.SerializeToString,
        response_deserializer=performance__pb2.PerfInitResponse.FromString,
        )
    self.PerfClear = channel.unary_unary(
        '/com.vmware.concord.performance.PerformanceService/PerfClear',
        request_serializer=performance__pb2.PerfCleanRequest.SerializeToString,
        response_deserializer=performance__pb2.PerfCleanResponse.FromString,
        )
    self.PerfWrite = channel.unary_unary(
        '/com.vmware.concord.performance.PerformanceService/PerfWrite',
        request_serializer=performance__pb2.PerfWriteRequest.SerializeToString,
        response_deserializer=performance__pb2.PerfWriteResponse.FromString,
        )


class PerformanceServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PerfInit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PerfClear(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PerfWrite(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PerformanceServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PerfInit': grpc.unary_unary_rpc_method_handler(
          servicer.PerfInit,
          request_deserializer=performance__pb2.PerfInitRequest.FromString,
          response_serializer=performance__pb2.PerfInitResponse.SerializeToString,
      ),
      'PerfClear': grpc.unary_unary_rpc_method_handler(
          servicer.PerfClear,
          request_deserializer=performance__pb2.PerfCleanRequest.FromString,
          response_serializer=performance__pb2.PerfCleanResponse.SerializeToString,
      ),
      'PerfWrite': grpc.unary_unary_rpc_method_handler(
          servicer.PerfWrite,
          request_deserializer=performance__pb2.PerfWriteRequest.FromString,
          response_serializer=performance__pb2.PerfWriteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.vmware.concord.performance.PerformanceService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
