# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: performance.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='performance.proto',
  package='com.vmware.concord.performance',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11performance.proto\x12\x1e\x63om.vmware.concord.performance\"^\n\x0fPerfInitRequest\x12\x13\n\x0b\x62lock_count\x18\x01 \x01(\x07\x12\x10\n\x08kv_count\x18\x02 \x01(\x07\x12\x10\n\x08key_size\x18\x03 \x01(\x07\x12\x12\n\nvalue_size\x18\x04 \x01(\x07\"4\n\x10PerfInitResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0cworkset_info\x18\x02 \x01(\t\"6\n\x11PerfWriteFromInit\x12\x0f\n\x07init_id\x18\x01 \x01(\t\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\x07\"{\n\x11PerfWriteExternal\x12\x11\n\tkv_prefix\x18\x01 \x01(\x07\x12\x10\n\x08kv_count\x18\x02 \x01(\x07\x12\x10\n\x08key_size\x18\x03 \x01(\x07\x12\x12\n\nvalue_size\x18\x04 \x01(\x07\x12\x1b\n\x13max_exec_time_milli\x18\x05 \x01(\x07\"\xc2\x01\n\x10PerfWriteRequest\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x46\n\tfrom_init\x18\x02 \x01(\x0b\x32\x31.com.vmware.concord.performance.PerfWriteFromInitH\x00\x12\x45\n\x08\x65xternal\x18\x03 \x01(\x0b\x32\x31.com.vmware.concord.performance.PerfWriteExternalH\x00\x42\x0e\n\x0cwrite_option\":\n\x11PerfWriteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x0cnew_block_id\x18\x02 \x01(\x06\"#\n\x10PerfCleanRequest\x12\x0f\n\x07init_id\x18\x01 \x01(\t\"$\n\x11PerfCleanResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xed\x02\n\x12PerformanceService\x12o\n\x08PerfInit\x12/.com.vmware.concord.performance.PerfInitRequest\x1a\x30.com.vmware.concord.performance.PerfInitResponse\"\x00\x12r\n\tPerfClear\x12\x30.com.vmware.concord.performance.PerfCleanRequest\x1a\x31.com.vmware.concord.performance.PerfCleanResponse\"\x00\x12r\n\tPerfWrite\x12\x30.com.vmware.concord.performance.PerfWriteRequest\x1a\x31.com.vmware.concord.performance.PerfWriteResponse\"\x00\x62\x06proto3')
)




_PERFINITREQUEST = _descriptor.Descriptor(
  name='PerfInitRequest',
  full_name='com.vmware.concord.performance.PerfInitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_count', full_name='com.vmware.concord.performance.PerfInitRequest.block_count', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kv_count', full_name='com.vmware.concord.performance.PerfInitRequest.kv_count', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='com.vmware.concord.performance.PerfInitRequest.key_size', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_size', full_name='com.vmware.concord.performance.PerfInitRequest.value_size', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=147,
)


_PERFINITRESPONSE = _descriptor.Descriptor(
  name='PerfInitResponse',
  full_name='com.vmware.concord.performance.PerfInitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='com.vmware.concord.performance.PerfInitResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workset_info', full_name='com.vmware.concord.performance.PerfInitResponse.workset_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=201,
)


_PERFWRITEFROMINIT = _descriptor.Descriptor(
  name='PerfWriteFromInit',
  full_name='com.vmware.concord.performance.PerfWriteFromInit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init_id', full_name='com.vmware.concord.performance.PerfWriteFromInit.init_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.performance.PerfWriteFromInit.block_id', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=203,
  serialized_end=257,
)


_PERFWRITEEXTERNAL = _descriptor.Descriptor(
  name='PerfWriteExternal',
  full_name='com.vmware.concord.performance.PerfWriteExternal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kv_prefix', full_name='com.vmware.concord.performance.PerfWriteExternal.kv_prefix', index=0,
      number=1, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kv_count', full_name='com.vmware.concord.performance.PerfWriteExternal.kv_count', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_size', full_name='com.vmware.concord.performance.PerfWriteExternal.key_size', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_size', full_name='com.vmware.concord.performance.PerfWriteExternal.value_size', index=3,
      number=4, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_exec_time_milli', full_name='com.vmware.concord.performance.PerfWriteExternal.max_exec_time_milli', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=382,
)


_PERFWRITEREQUEST = _descriptor.Descriptor(
  name='PerfWriteRequest',
  full_name='com.vmware.concord.performance.PerfWriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='com.vmware.concord.performance.PerfWriteRequest.payload', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_init', full_name='com.vmware.concord.performance.PerfWriteRequest.from_init', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='external', full_name='com.vmware.concord.performance.PerfWriteRequest.external', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='write_option', full_name='com.vmware.concord.performance.PerfWriteRequest.write_option',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=385,
  serialized_end=579,
)


_PERFWRITERESPONSE = _descriptor.Descriptor(
  name='PerfWriteResponse',
  full_name='com.vmware.concord.performance.PerfWriteResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.vmware.concord.performance.PerfWriteResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_block_id', full_name='com.vmware.concord.performance.PerfWriteResponse.new_block_id', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=581,
  serialized_end=639,
)


_PERFCLEANREQUEST = _descriptor.Descriptor(
  name='PerfCleanRequest',
  full_name='com.vmware.concord.performance.PerfCleanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init_id', full_name='com.vmware.concord.performance.PerfCleanRequest.init_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=641,
  serialized_end=676,
)


_PERFCLEANRESPONSE = _descriptor.Descriptor(
  name='PerfCleanResponse',
  full_name='com.vmware.concord.performance.PerfCleanResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.vmware.concord.performance.PerfCleanResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=678,
  serialized_end=714,
)

_PERFWRITEREQUEST.fields_by_name['from_init'].message_type = _PERFWRITEFROMINIT
_PERFWRITEREQUEST.fields_by_name['external'].message_type = _PERFWRITEEXTERNAL
_PERFWRITEREQUEST.oneofs_by_name['write_option'].fields.append(
  _PERFWRITEREQUEST.fields_by_name['from_init'])
_PERFWRITEREQUEST.fields_by_name['from_init'].containing_oneof = _PERFWRITEREQUEST.oneofs_by_name['write_option']
_PERFWRITEREQUEST.oneofs_by_name['write_option'].fields.append(
  _PERFWRITEREQUEST.fields_by_name['external'])
_PERFWRITEREQUEST.fields_by_name['external'].containing_oneof = _PERFWRITEREQUEST.oneofs_by_name['write_option']
DESCRIPTOR.message_types_by_name['PerfInitRequest'] = _PERFINITREQUEST
DESCRIPTOR.message_types_by_name['PerfInitResponse'] = _PERFINITRESPONSE
DESCRIPTOR.message_types_by_name['PerfWriteFromInit'] = _PERFWRITEFROMINIT
DESCRIPTOR.message_types_by_name['PerfWriteExternal'] = _PERFWRITEEXTERNAL
DESCRIPTOR.message_types_by_name['PerfWriteRequest'] = _PERFWRITEREQUEST
DESCRIPTOR.message_types_by_name['PerfWriteResponse'] = _PERFWRITERESPONSE
DESCRIPTOR.message_types_by_name['PerfCleanRequest'] = _PERFCLEANREQUEST
DESCRIPTOR.message_types_by_name['PerfCleanResponse'] = _PERFCLEANRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PerfInitRequest = _reflection.GeneratedProtocolMessageType('PerfInitRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERFINITREQUEST,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfInitRequest)
  ))
_sym_db.RegisterMessage(PerfInitRequest)

PerfInitResponse = _reflection.GeneratedProtocolMessageType('PerfInitResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERFINITRESPONSE,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfInitResponse)
  ))
_sym_db.RegisterMessage(PerfInitResponse)

PerfWriteFromInit = _reflection.GeneratedProtocolMessageType('PerfWriteFromInit', (_message.Message,), dict(
  DESCRIPTOR = _PERFWRITEFROMINIT,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfWriteFromInit)
  ))
_sym_db.RegisterMessage(PerfWriteFromInit)

PerfWriteExternal = _reflection.GeneratedProtocolMessageType('PerfWriteExternal', (_message.Message,), dict(
  DESCRIPTOR = _PERFWRITEEXTERNAL,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfWriteExternal)
  ))
_sym_db.RegisterMessage(PerfWriteExternal)

PerfWriteRequest = _reflection.GeneratedProtocolMessageType('PerfWriteRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERFWRITEREQUEST,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfWriteRequest)
  ))
_sym_db.RegisterMessage(PerfWriteRequest)

PerfWriteResponse = _reflection.GeneratedProtocolMessageType('PerfWriteResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERFWRITERESPONSE,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfWriteResponse)
  ))
_sym_db.RegisterMessage(PerfWriteResponse)

PerfCleanRequest = _reflection.GeneratedProtocolMessageType('PerfCleanRequest', (_message.Message,), dict(
  DESCRIPTOR = _PERFCLEANREQUEST,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfCleanRequest)
  ))
_sym_db.RegisterMessage(PerfCleanRequest)

PerfCleanResponse = _reflection.GeneratedProtocolMessageType('PerfCleanResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERFCLEANRESPONSE,
  __module__ = 'performance_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.performance.PerfCleanResponse)
  ))
_sym_db.RegisterMessage(PerfCleanResponse)



_PERFORMANCESERVICE = _descriptor.ServiceDescriptor(
  name='PerformanceService',
  full_name='com.vmware.concord.performance.PerformanceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=717,
  serialized_end=1082,
  methods=[
  _descriptor.MethodDescriptor(
    name='PerfInit',
    full_name='com.vmware.concord.performance.PerformanceService.PerfInit',
    index=0,
    containing_service=None,
    input_type=_PERFINITREQUEST,
    output_type=_PERFINITRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerfClear',
    full_name='com.vmware.concord.performance.PerformanceService.PerfClear',
    index=1,
    containing_service=None,
    input_type=_PERFCLEANREQUEST,
    output_type=_PERFCLEANRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerfWrite',
    full_name='com.vmware.concord.performance.PerformanceService.PerfWrite',
    index=2,
    containing_service=None,
    input_type=_PERFWRITEREQUEST,
    output_type=_PERFWRITERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PERFORMANCESERVICE)

DESCRIPTOR.services_by_name['PerformanceService'] = _PERFORMANCESERVICE

# @@protoc_insertion_point(module_scope)
