/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni */
#ifndef _Include_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni
#define _Include_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    initialize
 * Signature: (Ljava/lang/String;SLjava/lang/String;[Ljava/lang/String;SSLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_initialize
  (JNIEnv *, jobject, jstring, jshort, jstring, jobjectArray, jshort, jshort, jstring);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    subscribe
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_subscribe__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    subscribe
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_subscribe__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    unsubscribe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_unsubscribe
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    pop
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_pop
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    tryPop
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_tryPop
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    acknowledgeBlockId
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_acknowledgeBlockId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.ThinReplicaClientJni
 * Method:    getTestUpdate
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_ThinReplicaClientJni_getTestUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

