/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024 */
#ifndef _Include_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024
#define _Include_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    createTRC
 * Signature: (Ljava/lang/String;SLjava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_createTRC
  (JNIEnv *, jobject, jstring, jshort, jstring, jobjectArray);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    subscribe
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_subscribe__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    subscribe
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_subscribe__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    unsubscribe
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_unsubscribe
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    pop
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_pop
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    tryPop
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_tryPop
  (JNIEnv *, jobject);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    acknowledgeBlockId
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_acknowledgeBlockId
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com.digitalasset.daml.on.vmware.thin.replica.client.core.Library_00024
 * Method:    getTestUpdate
 * Signature: ()Lscala/Option;
 */
JNIEXPORT jobject JNICALL Java_com_digitalasset_daml_on_vmware_thin_replica_client_core_Library_00024_getTestUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

