version: "3.3"

services:
  fluentd:
    image: vmwblockchain/fluentd
    container_name: fluentd
    logging:
      driver: local
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./logging.env:/config/fluentd/logging.env
      - ./fluent-log-file.conf:/fluentd/etc/fluent-log-insight.conf
      - ./logs:/var/log/fluent
