f_val: 1
c_val: 0
num_replicas: 4
clients_per_participant_node: 5
prometheus_port: 9873
comm_to_use: tls
tls_certificates_folder_path: /daml-ledger-api/config-local/cert
tls_cipher_suite_list: ECDHE-ECDSA-AES256-GCM-SHA384
concord-bft_communication_buffer_length: 64000
client_initial_retry_timeout_milli: 150
client_min_retry_timeout_milli: 50
client_max_retry_timeout_milli: 1000
client_sends_request_to_all_replicas_first_thresh: 4
client_sends_request_to_all_replicas_period_thresh: 2
client_periodic_reset_thresh: 30
node:
  - replica:
      - replica_host: 10.0.0.1
        replica_port: 3501
participant_nodes:
  - participant_node:
      - participant_node_host: 0.0.0.0