client_proxies_per_replica: 4
daml_enable: false
FEATURE_time_service: true
eth_enable: false
concord-bft_communication_buffer_length: 33554432
concord-bft_max_external_message_size: 33554432
concord-bft_max_reply_message_size: 4096
concord-bft_max_num_of_reserved_pages: 8192
comm_to_use: tls
use_loopback_for_local_hosts: true
tls_cipher_suite_list: ECDHE-ECDSA-AES256-GCM-SHA384
tls_certificates_folder_path: /concord/config-local/cert
num_ro_replicas: 1
node__TEMPLATE:
  genesis_block: /concord/config-public/genesis.json
  blockchain_db_path: /concord/rocksdbdata/
  prometheus_port: 9891
  time_pusher_period_ms: 1000
ro_node__TEMPLATE:
  logger_config: /concord/config-public/log4cplus.properties
  bft_metrics_udp_port: 4501
  service_host: 0.0.0.0
  service_port: 5458
  s3-bucket-name: blockchain
  s3-access-key: concordbft
  s3-protocol: HTTP
  s3-url: minio:9000
  s3-secret-key: concordbft
node:
  - service_host: 0.0.0.0
    service_port: 5458
    daml_execution_engine_addr: daml_execution_engine:55000
    jaeger_agent: jaeger-agent:6831
    replica:
      - replica_host: 10.0.0.1
        replica_port: 3501
    client_proxy:
      - client_host: 10.0.0.1
        client_port: 3502
ro_node:
  - service_host: 0.0.0.0
    service_port: 5458
    jaeger_agent: jaeger-agent:5831
    logger_config: /concord/config-public/log4cplus.properties
    s3-bucket-name: blockchain
    s3-access-key: concordbft
    s3-protocol: HTTP
    s3-url: minio:9000
    s3-secret-key: concordbft