client_proxies_per_replica: 4
comm_to_use: tls
concord-bft_communication_buffer_length: 16777216
tls_certificates_folder_path: /config/concord/config-local/cert
tls_cipher_suite_list: ECDHE-ECDSA-AES256-GCM-SHA384
client_initial_retry_timeout_milli: 150
client_min_retry_timeout_milli: 50
client_max_retry_timeout_milli: 1000
client_sends_request_to_all_replicas_first_thresh: 2
client_sends_request_to_all_replicas_period_thresh: 2
client_periodic_reset_thresh: 30
client_number_of_standard_deviations_to_tolerate: 2
client_samples_per_evaluation: 32
client_samples_until_reset: 1000
prometheus_port: 9873
node:
  - replica:
      - replica_host: 10.0.0.1
        replica_port: 3501
operator_node:
  - operator_node_host: 0.0.0.0
    operator_id:
    operator_port: 3600

