# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daml_commit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daml_commit.proto',
  package='com.digitalasset.kvbc',
  syntax='proto3',
  serialized_options=_b('\n\025com.digitalasset.kvbc'),
  serialized_pb=_b('\n\x11\x64\x61ml_commit.proto\x12\x15\x63om.digitalasset.kvbc\"\x84\x01\n\rCommitRequest\x12\x12\n\nsubmission\x18\x01 \x01(\x0c\x12\x16\n\x0eparticipant_id\x18\x04 \x01(\t\x12\x16\n\x0e\x63orrelation_id\x18\x05 \x01(\t\x12\x14\n\x0cspan_context\x18\x06 \x01(\x0c\x12\r\n\x05\x66lags\x18\x07 \x01(\rJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04\"\x89\x01\n\x0e\x43ommitResponse\x12\x42\n\x06status\x18\x01 \x01(\x0e\x32\x32.com.digitalasset.kvbc.CommitResponse.CommitStatus\x12\x10\n\x08\x62lock_id\x18\x02 \x01(\x03\"!\n\x0c\x43ommitStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\x14\n\x05KVKey\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"|\n\x07\x43ommand\x12\x32\n\x04read\x18\x01 \x01(\x0b\x32\".com.digitalasset.kvbc.ReadCommandH\x00\x12\x36\n\x06\x63ommit\x18\x02 \x01(\x0b\x32$.com.digitalasset.kvbc.CommitRequestH\x00\x42\x05\n\x03\x63md\"R\n\x0bReadCommand\x12+\n\x05reads\x18\x01 \x03(\x0b\x32\x1c.com.digitalasset.kvbc.KVKey\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\"r\n\x0c\x43ommandReply\x12\x37\n\x06\x63ommit\x18\x01 \x01(\x0b\x32%.com.digitalasset.kvbc.CommitResponseH\x00\x12\x0e\n\x04read\x18\x02 \x01(\tH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\x42\x08\n\x06result2s\n\rCommitService\x12\x62\n\x11\x43ommitTransaction\x12$.com.digitalasset.kvbc.CommitRequest\x1a%.com.digitalasset.kvbc.CommitResponse\"\x00\x42\x17\n\x15\x63om.digitalasset.kvbcb\x06proto3')
)



_COMMITRESPONSE_COMMITSTATUS = _descriptor.EnumDescriptor(
  name='CommitStatus',
  full_name='com.digitalasset.kvbc.CommitResponse.CommitStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=284,
  serialized_end=317,
)
_sym_db.RegisterEnumDescriptor(_COMMITRESPONSE_COMMITSTATUS)


_COMMITREQUEST = _descriptor.Descriptor(
  name='CommitRequest',
  full_name='com.digitalasset.kvbc.CommitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='submission', full_name='com.digitalasset.kvbc.CommitRequest.submission', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='participant_id', full_name='com.digitalasset.kvbc.CommitRequest.participant_id', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='com.digitalasset.kvbc.CommitRequest.correlation_id', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='span_context', full_name='com.digitalasset.kvbc.CommitRequest.span_context', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='com.digitalasset.kvbc.CommitRequest.flags', index=4,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=177,
)


_COMMITRESPONSE = _descriptor.Descriptor(
  name='CommitResponse',
  full_name='com.digitalasset.kvbc.CommitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='com.digitalasset.kvbc.CommitResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.digitalasset.kvbc.CommitResponse.block_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMMITRESPONSE_COMMITSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=317,
)


_KVKEY = _descriptor.Descriptor(
  name='KVKey',
  full_name='com.digitalasset.kvbc.KVKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.digitalasset.kvbc.KVKey.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=339,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='com.digitalasset.kvbc.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='read', full_name='com.digitalasset.kvbc.Command.read', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit', full_name='com.digitalasset.kvbc.Command.commit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cmd', full_name='com.digitalasset.kvbc.Command.cmd',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=341,
  serialized_end=465,
)


_READCOMMAND = _descriptor.Descriptor(
  name='ReadCommand',
  full_name='com.digitalasset.kvbc.ReadCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reads', full_name='com.digitalasset.kvbc.ReadCommand.reads', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='participant_id', full_name='com.digitalasset.kvbc.ReadCommand.participant_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=549,
)


_COMMANDREPLY = _descriptor.Descriptor(
  name='CommandReply',
  full_name='com.digitalasset.kvbc.CommandReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commit', full_name='com.digitalasset.kvbc.CommandReply.commit', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read', full_name='com.digitalasset.kvbc.CommandReply.read', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='com.digitalasset.kvbc.CommandReply.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='result', full_name='com.digitalasset.kvbc.CommandReply.result',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=551,
  serialized_end=665,
)

_COMMITRESPONSE.fields_by_name['status'].enum_type = _COMMITRESPONSE_COMMITSTATUS
_COMMITRESPONSE_COMMITSTATUS.containing_type = _COMMITRESPONSE
_COMMAND.fields_by_name['read'].message_type = _READCOMMAND
_COMMAND.fields_by_name['commit'].message_type = _COMMITREQUEST
_COMMAND.oneofs_by_name['cmd'].fields.append(
  _COMMAND.fields_by_name['read'])
_COMMAND.fields_by_name['read'].containing_oneof = _COMMAND.oneofs_by_name['cmd']
_COMMAND.oneofs_by_name['cmd'].fields.append(
  _COMMAND.fields_by_name['commit'])
_COMMAND.fields_by_name['commit'].containing_oneof = _COMMAND.oneofs_by_name['cmd']
_READCOMMAND.fields_by_name['reads'].message_type = _KVKEY
_COMMANDREPLY.fields_by_name['commit'].message_type = _COMMITRESPONSE
_COMMANDREPLY.oneofs_by_name['result'].fields.append(
  _COMMANDREPLY.fields_by_name['commit'])
_COMMANDREPLY.fields_by_name['commit'].containing_oneof = _COMMANDREPLY.oneofs_by_name['result']
_COMMANDREPLY.oneofs_by_name['result'].fields.append(
  _COMMANDREPLY.fields_by_name['read'])
_COMMANDREPLY.fields_by_name['read'].containing_oneof = _COMMANDREPLY.oneofs_by_name['result']
_COMMANDREPLY.oneofs_by_name['result'].fields.append(
  _COMMANDREPLY.fields_by_name['error'])
_COMMANDREPLY.fields_by_name['error'].containing_oneof = _COMMANDREPLY.oneofs_by_name['result']
DESCRIPTOR.message_types_by_name['CommitRequest'] = _COMMITREQUEST
DESCRIPTOR.message_types_by_name['CommitResponse'] = _COMMITRESPONSE
DESCRIPTOR.message_types_by_name['KVKey'] = _KVKEY
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['ReadCommand'] = _READCOMMAND
DESCRIPTOR.message_types_by_name['CommandReply'] = _COMMANDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommitRequest = _reflection.GeneratedProtocolMessageType('CommitRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMMITREQUEST,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.CommitRequest)
  ))
_sym_db.RegisterMessage(CommitRequest)

CommitResponse = _reflection.GeneratedProtocolMessageType('CommitResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMMITRESPONSE,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.CommitResponse)
  ))
_sym_db.RegisterMessage(CommitResponse)

KVKey = _reflection.GeneratedProtocolMessageType('KVKey', (_message.Message,), dict(
  DESCRIPTOR = _KVKEY,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.KVKey)
  ))
_sym_db.RegisterMessage(KVKey)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), dict(
  DESCRIPTOR = _COMMAND,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.Command)
  ))
_sym_db.RegisterMessage(Command)

ReadCommand = _reflection.GeneratedProtocolMessageType('ReadCommand', (_message.Message,), dict(
  DESCRIPTOR = _READCOMMAND,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.ReadCommand)
  ))
_sym_db.RegisterMessage(ReadCommand)

CommandReply = _reflection.GeneratedProtocolMessageType('CommandReply', (_message.Message,), dict(
  DESCRIPTOR = _COMMANDREPLY,
  __module__ = 'daml_commit_pb2'
  # @@protoc_insertion_point(class_scope:com.digitalasset.kvbc.CommandReply)
  ))
_sym_db.RegisterMessage(CommandReply)


DESCRIPTOR._options = None

_COMMITSERVICE = _descriptor.ServiceDescriptor(
  name='CommitService',
  full_name='com.digitalasset.kvbc.CommitService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=667,
  serialized_end=782,
  methods=[
  _descriptor.MethodDescriptor(
    name='CommitTransaction',
    full_name='com.digitalasset.kvbc.CommitService.CommitTransaction',
    index=0,
    containing_service=None,
    input_type=_COMMITREQUEST,
    output_type=_COMMITRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMITSERVICE)

DESCRIPTOR.services_by_name['CommitService'] = _COMMITSERVICE

# @@protoc_insertion_point(module_scope)
