# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thin_replica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='thin_replica.proto',
  package='com.vmware.concord.thin_replica',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12thin_replica.proto\x12\x1f\x63om.vmware.concord.thin_replica\x1a\x1bgoogle/protobuf/empty.proto\"&\n\x10ReadStateRequest\x12\x12\n\nkey_prefix\x18\x01 \x01(\x0c\"<\n\x14ReadStateHashRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x12\n\nkey_prefix\x18\x02 \x01(\x0c\";\n\x13SubscriptionRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x12\n\nkey_prefix\x18\x02 \x01(\x0c\"\x1b\n\x07\x42lockId\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\"O\n\x04\x44\x61ta\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x35\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\'.com.vmware.concord.thin_replica.KVPair\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"&\n\x04Hash\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x32\xe2\x04\n\x0bThinReplica\x12g\n\tReadState\x12\x31.com.vmware.concord.thin_replica.ReadStateRequest\x1a%.com.vmware.concord.thin_replica.Data0\x01\x12m\n\rReadStateHash\x12\x35.com.vmware.concord.thin_replica.ReadStateHashRequest\x1a%.com.vmware.concord.thin_replica.Hash\x12s\n\x12SubscribeToUpdates\x12\x34.com.vmware.concord.thin_replica.SubscriptionRequest\x1a%.com.vmware.concord.thin_replica.Data0\x01\x12M\n\tAckUpdate\x12(.com.vmware.concord.thin_replica.BlockId\x1a\x16.google.protobuf.Empty\x12x\n\x17SubscribeToUpdateHashes\x12\x34.com.vmware.concord.thin_replica.SubscriptionRequest\x1a%.com.vmware.concord.thin_replica.Hash0\x01\x12=\n\x0bUnsubscribe\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_READSTATEREQUEST = _descriptor.Descriptor(
  name='ReadStateRequest',
  full_name='com.vmware.concord.thin_replica.ReadStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_prefix', full_name='com.vmware.concord.thin_replica.ReadStateRequest.key_prefix', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=122,
)


_READSTATEHASHREQUEST = _descriptor.Descriptor(
  name='ReadStateHashRequest',
  full_name='com.vmware.concord.thin_replica.ReadStateHashRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.thin_replica.ReadStateHashRequest.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_prefix', full_name='com.vmware.concord.thin_replica.ReadStateHashRequest.key_prefix', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=184,
)


_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='com.vmware.concord.thin_replica.SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.thin_replica.SubscriptionRequest.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_prefix', full_name='com.vmware.concord.thin_replica.SubscriptionRequest.key_prefix', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=245,
)


_BLOCKID = _descriptor.Descriptor(
  name='BlockId',
  full_name='com.vmware.concord.thin_replica.BlockId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.thin_replica.BlockId.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=274,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='com.vmware.concord.thin_replica.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.thin_replica.Data.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='com.vmware.concord.thin_replica.Data.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=355,
)


_KVPAIR = _descriptor.Descriptor(
  name='KVPair',
  full_name='com.vmware.concord.thin_replica.KVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='com.vmware.concord.thin_replica.KVPair.key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='com.vmware.concord.thin_replica.KVPair.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=393,
)


_HASH = _descriptor.Descriptor(
  name='Hash',
  full_name='com.vmware.concord.thin_replica.Hash',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='com.vmware.concord.thin_replica.Hash.block_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='com.vmware.concord.thin_replica.Hash.hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=433,
)

_DATA.fields_by_name['data'].message_type = _KVPAIR
DESCRIPTOR.message_types_by_name['ReadStateRequest'] = _READSTATEREQUEST
DESCRIPTOR.message_types_by_name['ReadStateHashRequest'] = _READSTATEHASHREQUEST
DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['BlockId'] = _BLOCKID
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['KVPair'] = _KVPAIR
DESCRIPTOR.message_types_by_name['Hash'] = _HASH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadStateRequest = _reflection.GeneratedProtocolMessageType('ReadStateRequest', (_message.Message,), dict(
  DESCRIPTOR = _READSTATEREQUEST,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.ReadStateRequest)
  ))
_sym_db.RegisterMessage(ReadStateRequest)

ReadStateHashRequest = _reflection.GeneratedProtocolMessageType('ReadStateHashRequest', (_message.Message,), dict(
  DESCRIPTOR = _READSTATEHASHREQUEST,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.ReadStateHashRequest)
  ))
_sym_db.RegisterMessage(ReadStateHashRequest)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTIONREQUEST,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.SubscriptionRequest)
  ))
_sym_db.RegisterMessage(SubscriptionRequest)

BlockId = _reflection.GeneratedProtocolMessageType('BlockId', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKID,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.BlockId)
  ))
_sym_db.RegisterMessage(BlockId)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.Data)
  ))
_sym_db.RegisterMessage(Data)

KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), dict(
  DESCRIPTOR = _KVPAIR,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.KVPair)
  ))
_sym_db.RegisterMessage(KVPair)

Hash = _reflection.GeneratedProtocolMessageType('Hash', (_message.Message,), dict(
  DESCRIPTOR = _HASH,
  __module__ = 'thin_replica_pb2'
  # @@protoc_insertion_point(class_scope:com.vmware.concord.thin_replica.Hash)
  ))
_sym_db.RegisterMessage(Hash)



_THINREPLICA = _descriptor.ServiceDescriptor(
  name='ThinReplica',
  full_name='com.vmware.concord.thin_replica.ThinReplica',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=436,
  serialized_end=1046,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadState',
    full_name='com.vmware.concord.thin_replica.ThinReplica.ReadState',
    index=0,
    containing_service=None,
    input_type=_READSTATEREQUEST,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ReadStateHash',
    full_name='com.vmware.concord.thin_replica.ThinReplica.ReadStateHash',
    index=1,
    containing_service=None,
    input_type=_READSTATEHASHREQUEST,
    output_type=_HASH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeToUpdates',
    full_name='com.vmware.concord.thin_replica.ThinReplica.SubscribeToUpdates',
    index=2,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_DATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AckUpdate',
    full_name='com.vmware.concord.thin_replica.ThinReplica.AckUpdate',
    index=3,
    containing_service=None,
    input_type=_BLOCKID,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeToUpdateHashes',
    full_name='com.vmware.concord.thin_replica.ThinReplica.SubscribeToUpdateHashes',
    index=4,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_HASH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Unsubscribe',
    full_name='com.vmware.concord.thin_replica.ThinReplica.Unsubscribe',
    index=5,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_THINREPLICA)

DESCRIPTOR.services_by_name['ThinReplica'] = _THINREPLICA

# @@protoc_insertion_point(module_scope)
