# pre-deploy the QuickStart DApp from DAML website (https://docs.daml.com/getting-started/quickstart.html)
# example:  daml deploy --host=10.40.205.67 --port=6865

simpleConfig:
  blockchain: concord
  nodes:
    - ip:
      port: 6865
      percentage: 100
    - ip:
      port: 6865
      percentage: 0
    - ip:
      port: 6865
      percentage: 0
    - ip:
      percentage: 0
      port: 6865
  workloads:
    - dapp: IOU
      rateControl: 0 # Throttled RPS
      logging: false
      logUpdateFreq: 10 # Number of request after which logs are updated
      params:
        - Alice # Party
        - 10 # Total no. of requests
        - 1 # No. or commands packed in each request
  numberThreads: 1 # # No of concurrent requests

advancedConfig:
  wavefront:
    enabled: false
    proxyHost: 10.40.205.202
    metricsPort: 2878
    source:  blockchain-benchmark
    metricName: gRPC.response.ms
