# prerequisite: Enable PEE

simpleConfig:
  blockchain: concord
  nodes: # committer nodes
    - ip:
      port: 50051
      percentage: 100
    - ip:
      port: 50051
      percentage: 0
    - ip:
      port: 50051
      percentage: 0
    - ip:
      port: 50051
      percentage: 0
    - ip:
      port: 50051
      percentage: 0
    - ip:
      port: 50051
      percentage: 0
    - ip:
      port: 50051
      percentage: 0
  workloads:
    - dapp: PEE
      rateControl: 0 # Throttled RPS
      logging: false
      logUpdateFreq: 10 # Number of request after which logs are updated
      params:
        - PerfWrite # Operation name
        - 100 # Total no. of requests
        - 151 # No. of KV pairs in each block
        - 76 # Key size
        - 502 # Value size
        - 0 # Batch of <n> blocks pre-created in Concord memory.
        - 15100 # Payload size in bytes
  numberThreads: 1 # No of concurrent requests
advancedConfig:
  wavefront:
    enabled: false